### ISSUE TITLE
Dev branch still relevant?

### ISSUE THREAD

**Issue by mo-g** [aelveborn/Wii-Scale#38]
Currently the readme asks users to PR against dev, but dev is very out of date, and all recent merges have been direct to master.

Is there a plan to move to the more standard practice of master as unstable, branch for release - or does dev just need updating?

It the first one, readme needs changing to tell people to PR against master. If it's the second one, dev needs to be synchronised against master, and merges into master from elsewhere but dev need to stop. :)

Thanks to @sahoahfoa for making me notice this, my apologies to you for not realising till I tried the merge for myself!

**Comment by aelveborn** [comment]
So, the initial plan was to use a dev branch during development, create release branches during testing and master as the stable version. But, since we are not working with versions at all, and there is not a ton of code being written daily, it's just easier using the master as for now. I'll update the readme.

Thanks for pointing this out :)
